import 'reflect-metadata';
import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './dist/app.module.js';

const app = await NestFactory.create(AppModule, { logger: false });
app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true, forbidNonWhitelisted: true }));
await app.listen(0);
const B = `http://127.0.0.1:${app.getHttpServer().address().port}`;
const j = async (m,p,b)=>{const r=await fetch(B+p,{method:m,headers:{'content-type':'application/json'},body:b?JSON.stringify(b):undefined});return{status:r.status,body:await r.json()};};
let pass=0,fail=0; const P=(l,c)=>{c?pass++:fail++;console.log(`${c?'PASS':'FAIL'}  ${l}`);};

let r=await j('POST','/events/collection',{speciesCode:'ASWG',quantityKg:60,plantPart:'ROOT',collectorId:'NMPB-COL-KA-8823',season:'RABI',location:{lat:13.3409,lon:77.1018,altitudeM:842},entryMethod:'TIER1_PWA',photoIpfsCID:'QmA'});
const farmA=r.body.data.epc; P('1  valid collection commits',r.body.ok&&/CE-KA-ASWG/.test(farmA));
r=await j('POST','/events/collection',{speciesCode:'ASWG',quantityKg:20,plantPart:'ROOT',collectorId:'NMPB-COL-KA-8823',season:'RABI',location:{lat:19.076,lon:72.8777,altitudeM:14},entryMethod:'TIER1_PWA'});
P('2  out-of-zone -> 422 ZONE_VIOLATION',r.status===422&&r.body.code==='ZONE_VIOLATION');
r=await j('POST','/events/collection',{speciesCode:'ASWG',quantityKg:5,plantPart:'LEAF',collectorId:'NMPB-COL-KA-8823',season:'RABI',location:{lat:13.3409,lon:77.1018,altitudeM:842},entryMethod:'TIER1_PWA'});
P('2b wrong part -> PART_VIOLATION',r.body.code==='PART_VIOLATION');
r=await j('POST','/events/collection',{speciesCode:'ASWG',quantityKg:-1,plantPart:'ROOT',collectorId:'x',season:'RABI',location:{lat:1,lon:1,altitudeM:1},entryMethod:'TIER1_PWA'});
P('2c invalid DTO -> 400 validation',r.status===400);
r=await j('POST','/events/collection',{speciesCode:'ASWG',quantityKg:40,plantPart:'ROOT',collectorId:'NMPB-COL-KA-9910',season:'RABI',location:{lat:13.3401,lon:75.77,altitudeM:910},entryMethod:'TIER1_PWA',photoIpfsCID:'QmB'});
const farmB=r.body.data.epc;
r=await j('POST','/events/transformation',{kind:'MERGE',inputs:[{epc:farmA,quantityKg:60},{epc:farmB,quantityKg:40}],outputKg:89,declaredLossFactor:0.1,zoneId:'NMPB-KA-ZONE-07',dryingGapSeconds:3600});
const merged=r.body.data.outputEpc; P('3  merge A+B keeps both inputs',r.body.ok&&r.body.data.inputEpcs.length===2);
r=await j('POST','/events/transformation',{kind:'MERGE',inputs:[{epc:farmA,quantityKg:60},{epc:farmB,quantityKg:40}],outputKg:110,declaredLossFactor:0.1,zoneId:'NMPB-KA-ZONE-07'});
P('4  dilution -> MASS_BALANCE_VIOLATION',r.status===422&&r.body.code==='MASS_BALANCE_VIOLATION');
r=await j('POST','/events/quality-test',{epc:merged,metrics:[{name:'lead',value:1,unit:'ppm',limit:10,withinLimit:true}],ipfsCID:'QmC',testingLabMsp:'LabMSP',verifierMsp:'LabMSP',verifierRole:'SECOND_LAB'});
P('5a same signer twice -> ENDORSEMENT_MISSING',r.body.code==='ENDORSEMENT_MISSING');
r=await j('POST','/events/quality-test',{epc:merged,metrics:[{name:'lead',value:1.2,unit:'ppm',limit:10,withinLimit:true},{name:'arsenic',value:0.3,unit:'ppm',limit:3,withinLimit:true},{name:'moisture',value:8,unit:'%',limit:12,withinLimit:true}],dna:{declaredSpecies:'Withania somnifera',confirmedSpecies:'Withania somnifera'},ipfsCID:'QmC',testingLabMsp:'LabMSP',verifierMsp:'NmpbMSP',verifierRole:'REGULATOR'});
P('5b lab+regulator co-endorse -> PASSED',r.body.ok&&r.body.data.result==='PASSED');
r=await j('POST','/events/formulation',{inputEpcs:[merged],productName:'Ashwagandha Root Churna 60g',unitCount:3,manufacturerMsp:'ManufacturerMSP'});
const product=r.body.data.productEpc,token=r.body.data.units[0].token;
P('6  formulation mints 3 signed QRs',r.body.ok&&r.body.data.units.length===3&&token.includes('.'));
r=await j('GET','/qr/'+encodeURIComponent(token)+'/verify');
P('7  genuine QR verifies authentic (score 100)',r.body.data.signatureValid&&r.body.data.verifiedAuthentic&&r.body.data.gacpScore===100);
r=await j('GET','/qr/'+encodeURIComponent(token.slice(0,-4)+'dead')+'/verify');
P('7b tampered QR fails signature',r.body.data.signatureValid===false&&r.body.data.valid===false);
r=await j('GET','/batch/'+encodeURIComponent(product));
const steps=r.body.data.timeline.map(t=>t.step);
P('8  timeline: 2 collections + testing + formulation',steps.filter(s=>s==='COLLECTION').length>=2&&steps.includes('TESTING')&&steps.includes('FORMULATION'));
r=await j('GET','/zones/'+encodeURIComponent('NMPB-KA-ZONE-07')+'/quota');
const aswg=r.body.data.quotas.find(q=>q.speciesCode==='ASWG');
P('9  zone-7 ASWG quota -> 280kg RED',aswg.consumedKg===280&&aswg.band==='RED');
r=await j('POST','/recall/'+encodeURIComponent(merged));
P('10 recall traces merged lot to both farms + product',r.body.data.sourceLots.length===2&&r.body.data.affectedProducts.includes(product));
console.log(`\n${pass}/${pass+fail} gateway HTTP checks passed`);
await app.close();
process.exit(fail?1:0);
